version: '3.4'
name: cs-5-homework
services:
  ozon.route256.five.orderservice:
    image: ${DOCKER_REGISTRY-}ozonroute256fiveorderservice
    ports:
     - "50060-50061:50001"
     - "50070-50071:50002"
    environment:
     - ROUTE256_SERVICE_DISCOVERY_ADDRESS=http://host.docker.internal:5084
     - ROUTE256_LOGISTICS_SIMULATOR_ADDRESS=http://host.docker.internal:5085
     - ROUTE256_CUSTOMER_SERVICE_ADDRESS=http://host.docker.internal:5081
     - Postgres__Db=orders_db
     - Postgres__Login=postgres
     - Postgres__Password=secret
     - Postgres__Cluster=orders-cluster
    build:
      context: .
      dockerfile: src/Ozon.Route256.Five.OrderService.Host/Dockerfile
    deploy:
      replicas: 2
    depends_on:
     - service-discovery
     - customer-service
     - logistics-simulator
     - kafka
     - orders-db-1
     - orders-db-2
     - redis-orders
     - orders-service-jaeger
    restart: unless-stopped

  redis-customers:
    image: redis
    restart: unless-stopped
    volumes:
      - "redis_customers_data:/data"

  redis-orders:
    image: redis
    restart: unless-stopped
    ports:
      - "6382:6379"
    volumes:
      - "redis_orders_data:/data"

  redis-logistics:
    image: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - "redis_logistics_data:/data"

  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
    restart: unless-stopped
    volumes:
     - "zookeeper_data:/data"
     - "zookeeper_datalog:/datalog"
     - "zookeeper_logs:/logs"

  kafka:
    image: bitnami/kafka:latest
    ports:
     - "9092:9092"
     - '9093:9093'
    environment:
     - KAFKA_BROKER_ID=1
     - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
     - ALLOW_PLAINTEXT_LISTENER=yes
     - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
     - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
     - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
     - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
     - zookeeper
    restart: unless-stopped
    volumes:
     - "kafka_data:/bitnami"

  orders-db-1:
    image: postgres:latest
    ports:
     - "5433:5432"
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_DB=orders_db
     - POSTGRES_PASSWORD=secret
    volumes:
     - pgdata_orders_1:/var/lib/postgresql/data
    restart: unless-stopped

  orders-db-2:
    image: postgres:latest
    ports:
     - "5434:5432"
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_DB=orders_db
     - POSTGRES_PASSWORD=secret
    volumes:
     - pgdata_orders_2:/var/lib/postgresql/data
    restart: unless-stopped

  customers-db:
    image: postgres:latest
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_DB=customers_db
     - POSTGRES_PASSWORD=secret
    volumes:
     - pgdata_customers:/var/lib/postgresql/data
    restart: unless-stopped

  adminer:
    image: adminer
    ports:
     - "6432:8080"
    restart: unless-stopped

  pgadmin4:
    image: dpage/pgadmin4
    ports:
     - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: unless-stopped
    volumes:
     - pgadmin4_data:/var/lib/pgadmin

  orders-service-jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    restart: unless-stopped
    volumes:
     - "jaegertracing_tmp:/tmp"

  customer-service:
    image: gitlab-registry.ozon.dev/cs/classroom-5/teachers/five/customer-service:latest
    ports:
     - "5081:80"
    depends_on:
     - customers-db
     - service-discovery
     - redis-customers
    restart: unless-stopped
    environment:
     ConnectionStrings:SdUrl: http://host.docker.internal:5084

  logistics-simulator:
    image: gitlab-registry.ozon.dev/cs/classroom-5/teachers/five/logistics-simulator:latest
    ports:
     - "5085:5080"
    environment:
      Redis:ConnectionString: redis-logistics:6379,abortConnect=false
      Kafka:BootstrapServers: kafka:9092
    depends_on:
     - kafka
     - redis-logistics
    restart: unless-stopped

  orders-generator-api:
    image: gitlab-registry.ozon.dev/cs/classroom-5/teachers/five/orders-generator:latest
    environment:
     - ROUTE256_KAFKA_BROKERS=kafka:9092
     - ROUTE256_ORDER_SOURCE=Api
     - ROUTE256_ORDER_REQUEST_TOPIC=pre_orders
     - ROUTE256_CUSTOMER_SERVICE=http://host.docker.internal:5081
    depends_on:
     - kafka
     - customer-service
    restart: unless-stopped

  orders-generator-website:
    image: gitlab-registry.ozon.dev/cs/classroom-5/teachers/five/orders-generator:latest
    environment:
     - ROUTE256_KAFKA_BROKERS=kafka:9092
     - ROUTE256_ORDER_SOURCE=WebSite
     - ROUTE256_ORDER_REQUEST_TOPIC=pre_orders
     - ROUTE256_CUSTOMER_SERVICE=http://host.docker.internal:5081
    depends_on:
     - kafka
     - customer-service
    restart: unless-stopped

  orders-generator-mobile:
    image: gitlab-registry.ozon.dev/cs/classroom-5/teachers/five/orders-generator:latest
    environment:
     - ROUTE256_KAFKA_BROKERS=kafka:9092
     - ROUTE256_ORDER_SOURCE=Mobile
     - ROUTE256_ORDER_REQUEST_TOPIC=pre_orders
     - ROUTE256_CUSTOMER_SERVICE=http://host.docker.internal:5081
    depends_on:
     - kafka
     - customer-service
    restart: unless-stopped

  service-discovery:
    image: gitlab-registry.ozon.dev/cs/classroom-5/teachers/five/service-discovery:latest
    ports:
     - "5084:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ROUTE256_DB_STATE=orders-cluster:0-3:host.docker.internal:5433;orders-cluster:4-7:host.docker.internal:5434
      - ROUTE256_UPDATE_TIMEOUT=10
    restart: unless-stopped

volumes:
  pgdata_customers:
  pgdata_orders_1:
  pgdata_orders_2:
  pgadmin4_data:
  kafka_data:
  zookeeper_data:
  zookeeper_datalog:
  zookeeper_logs:
  redis_logistics_data:
  redis_orders_data:
  redis_customers_data:
  jaegertracing_tmp:
