version: '3.4'
name: cs-5-homework
services:
  ozon.route256.five.orderservice:
    image: ${DOCKER_REGISTRY-}ozonroute256fiveorderservice
    ports:
     - "50060-50061:50001"
     - "50070-50071:50002"
    environment:
     - ROUTE256_SERVICE_DISCOVERY_ADDRESS=http://host.docker.internal:5084
     - ROUTE256_LOGISTICS_SIMULATOR_ADDRESS=http://host.docker.internal:5082
    build:
      context: .
      dockerfile: src/Ozon.Route256.Five.OrderService/Dockerfile
    deploy:
      replicas: 2
    depends_on:
     - service-discovery
     - customer-service
     - logistics-simulator
     - kafka
     - orders-db
     - redis-orders
     - jaeger
    restart: unless-stopped

  redis-customers:
    image: redis
    restart: unless-stopped

  redis-orders:
    image: redis
    restart: unless-stopped

  redis-logistics:
    image: redis
    restart: unless-stopped

  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
    restart: unless-stopped

  kafka:
    image: bitnami/kafka:latest
    ports:
     - "9092:9092"
    environment:
     - KAFKA_BROKER_ID=1
     - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
     - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
     - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
     - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
     - zookeeper
    restart: unless-stopped

  orders-db:
    image: postgres:latest
    ports:
     - "5433:5432"
    environment:
     - POSTGRES_DB=orders_db
     - POSTGRES_PASSWORD=secret
    volumes:
     - pgdata_orders:/var/lib/postgresql/data
    restart: unless-stopped

  customers-db:
    image: postgres:latest
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_DB=customers_db
     - POSTGRES_PASSWORD=secret
    volumes:
     - pgdata_customers:/var/lib/postgresql/data
    restart: unless-stopped

  adminer:
    image: adminer
    ports:
     - "6432:8080"
    restart: unless-stopped

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    restart: unless-stopped

  customer-service:
    image: gitlab-registry.ozon.dev/cs/classroom-5/teachers/five/customer-service:latest
    ports:
     - "5081:80"
    depends_on:
     - customers-db
     - service-discovery
     - redis-customers
    restart: unless-stopped

  logistics-simulator:
    image: gitlab-registry.ozon.dev/cs/classroom-5/teachers/five/logistics-simulator:latest
    ports:
     - "5082:5080"
    depends_on:
     - kafka
     - redis-logistics
    restart: unless-stopped

  orders-generator:
    image: gitlab-registry.ozon.dev/cs/classroom-5/teachers/five/orders-generator:latest
    ports:
     - "5083:80"
    depends_on:
     - kafka
     - customer-service
    restart: unless-stopped

  service-discovery:
    image: gitlab-registry.ozon.dev/cs/classroom-5/teachers/five/service-discovery:latest
    ports:
     - "5084:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ROUTE256_DB_STATE=cluster:0-9:db1:1543;cluster:10-19:db2:1543;cluster1:0:db3:1543
      - ROUTE256_UPDATE_TIMEOUT=10
    restart: unless-stopped

volumes:
  pgdata_customers:
  pgdata_orders:
